### ISSUE TITLE
Validation of newly added parameters for network creation in Cloudify and HEAT Orchestrator

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#1]
_From @amolbjadhav on July 11, 2018 9:11_

_Copied from original issue: vanlittle/VNF-Onboarding#91_

**Comment by nandkumarj** [comment]
There are around 8 parameters newly added to VNF Onboarding UI . Validation for which will be addressed under this issue.

**Comment by amolbjadhav** [comment]
The issue is Fixed.  All these parameters are mandatory. we have checked in the code.
