### ISSUE TITLE
Update wiki for Forget Password page

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#13]
_From @nandkumarj on May 30, 2018 12:47_

VNF Onboarding tool allows user to generate a new random password incase he/she has forgotten password set up at the time of user signup.  wiki needs to be updated for that page.

_Copied from original issue: vanlittle/VNF-Onboarding#70_

**Comment by nandkumarj** [comment]
wiki updated for 'forget password' page details

**Comment by ljilluzzi** [comment]
OK to close
