### ISSUE TITLE
Firefox incompatibilities

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#15]
_From @vanlittle on May 24, 2018 19:4_

UI Tool not working properly with firefox.    'Continue button does not work on first wizard screen'

How to reproduce the error:
1. login
2. fill out parameters on screen 1 of wizard
3. click continue -> Bug: continue button does nothing

_Copied from original issue: vanlittle/VNF-Onboarding#59_

**Comment by ljilluzzi** [comment]
Tested tool on latest firefox, issue with spin button rendering.  Work In-Progress. Remove spin button, replace with drop down. ETA 10/09

**Comment by amolbjadhav** [comment]
The issue is fixed. Code is tested and checked in.

**Comment by harshwardhas** [comment]
The code is tested with latest Firefox version: 62.0.2 (64 bit).
