### ISSUE TITLE
Riftware  does not support git upload operation

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#18]
_From @nandkumarj on April 16, 2018 9:41_

Right not Riftware blueprint generated through Onboarding application cannot be uploaded to git.

_Copied from original issue: vanlittle/VNF-Onboarding#46_

**Comment by nandkumarj** [comment]
Doubt it would make sense to address this in isolation. Plan is to take this up at the time Riftware MultiVDU.

**Comment by nandkumarj** [comment]
This is addressed #37. So this is a duplicate. Code changes are checked in and tested. So closing this issue.
