### ISSUE TITLE
Creation of new network for Cloudify + VCD

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#2]
_From @nandkumarj on July 10, 2018 8:35_

_Copied from original issue: vanlittle/VNF-Onboarding#90_

**Comment by ljilluzzi** [comment]
#In-Progress
UI Changes to capture required parameters.
#To-Do
Backend changes. Create and populate derived datastructures required for jinja2 template. 
Update Jinja2 template
Testing

**Comment by amolbjadhav** [comment]
Checked in the code and validated the changes.
