### ISSUE TITLE
Rift.io blueprint generation does not confirm to design

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#24]
_From @nandkumarj on March 9, 2018 11:38_

Mechanism implemented for Rift.io blueprint generation is not consistent with design.  Need  Rift.io to follow same mechanism as is done for other orchestrators.

_Copied from original issue: vanlittle/VNF-Onboarding#31_

**Comment by nandkumarj** [comment]
This is a duplicate for #37.
This is implemented and tested, hence closing this issue.
