### ISSUE TITLE
Pull request for following changes

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#3]
_From @nandkumarj on July 2, 2018 12:59_

1. Pages, collapsible windows, input fields which are not valid for OSM + Orchestrator combination should not be part of Blurprint generation flow (#86,#87,#13)

2. MultiVDU Support for TOSCA (#82)

3. Flask server should not run in debug mode(#71)

_Copied from original issue: vanlittle/VNF-Onboarding/pull/89_

**Comment by varadep** [comment]
request merged, closing issue
