### ISSUE TITLE
GUI: Add EPA options for Cloudify 

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#30]
_From @vanlittle on February 26, 2018 12:47_

Build support and enable EPA Attributes for Cloudify 4.0 and 3.4 in the GUI

_Copied from original issue: vanlittle/VNF-Onboarding#17_

**Comment by nandkumarj** [comment]
Test comment

**Comment by ljilluzzi** [comment]
Test Comment

**Comment by amolbjadhav** [comment]
The issue is Fixed. We have implemented and tested the code.
