### ISSUE TITLE
MultiVDU Support for VCD + OVF - backend changes. ETA -  08/06

### ISSUE THREAD

**Issue by nandkumarj** [vmware/bellhop#34]
Need a capability to create  MultiVDU VNF for VCD platform using OVF format.

**Comment by nandkumarj** [comment]
In the process of finalizing requirements for this task . Will be able to provide ETA once that is done.

**Comment by ljilluzzi** [comment]
Issues with vCD; may need Ravish or Pankaj

**Comment by ljilluzzi** [comment]
Amol to send vCD template to the entire team on 07/31

**Comment by amolbjadhav** [comment]
vCD template has been sent to team for their suggestions

**Comment by amolbjadhav** [comment]
We have added the feature. The code is checked in.
