### ISSUE TITLE
Multi-VDU Riftware + OpenStack

### ISSUE THREAD

**Issue by ljilluzzi** [vmware/bellhop#37]

**Comment by ljilluzzi** [comment]
Need Riftware 6.1 environment built

**Comment by ljilluzzi** [comment]
Need reference template from Riftware; will help reduce investigation time. Possible license issue.

**Comment by nandkumarj** [comment]
Updates
1. Generated a MultiVDU VNFD and NSD using Riftware UI  and deployed it succesfully in VIO. This was done to understand schema and differences with OSM.
2. Discussed some issues with expert from Riftware.
3. Generated a MultiVDU VNFD and NSD from backend scripts bypasing the UI. And tested deployment. This is to derive minimal VNFD and NSD for MultiVDU Riftware.

**Comment by nandkumarj** [comment]
Items to be investigated/tested
1. Find out Supported NIC types for Riftware + VIO. Test deployment with different nic types. Tested NIC types will be incorporated in the code.
2. Understand EPA params support in Riftware. And try out deployment with common EPA params that
   VNF Onboarding tool support across orchestrators.  Reference template tested had only one EPA 
   Param.
3. Test deployment with cloud_init input. For this would require an image with cloud_init support.
4. Test scenario where VNFD and NSD utilises existing network in the VIM. Reference blueprint tested had all the newly created network.

**Comment by nandkumarj** [comment]
As per riftio documentation 
https://open.riftio.com/documentation/riftware/6.1/a/descriptor/vnfd/vnfd-vdu-interface.htm? 

Following nic types are supported
Type of virtual interface between VM and host:

VIRTIO: [Default] Use the traditional VIRTIO interface

PCI-PASSTHROUGH: Use PCI-PASSTHROUGH interface

SR-IOV: Use SR-IOV interface

E1000 : Emulate E1000 interface

RTL8139 : Emulate RTL8139 interface

PCNET : Emulate PCNET interface

OM-MGMT: Used to specify OpenMANO management internal-connection type

**Comment by nandkumarj** [comment]
Update:  End to End changes  from UI to backend are implemented.  Could generate  multivdu blueprint package for Riftware 6.1 from VNF Onboarding tool . Also able to onboard blueprint packages to Riftware 6.1. Testing is in progress.

**Comment by ljilluzzi** [comment]
Investigating issues  with NICs  & IPs

**Comment by nandkumarj** [comment]
Once list of network interfaces actually supported by Riftware is provided , that list will be updated in the tool.

**Comment by ljilluzzi** [comment]
Check with Kishor; then update comments or close (by 11/13).
Where is PCI passthrough?
Remove E1000E

**Comment by amolbjadhav** [comment]
RIFTware 6.1 supports following 4 nic types:
VMXNET3
VIRTIO
E1000
SRIOV

We have added and tested these NIC types. Hence closing the issue
