### ISSUE TITLE
MultiVDU Support for OpenStack + HEAT

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#4]
_From @nandkumarj on June 18, 2018 8:57_

VNF Onboarding tool should be able to generate a blueprint for VNF consisting of Multiple VMs for Openstack VIM and Heat Orchestrator combination.

_Copied from original issue: vanlittle/VNF-Onboarding#85_

**Comment by ljilluzzi** [comment]
Frontend Changes
- Added an orchestrator "NONE" on VNF Definitions page
- Modified Network Configurations page as OS does not have mgmt network
- Added a parameter "subnet" for networks which are newly created
- Added EPA Parameters page 
Backend Changes
- Backend changes to capture OS + HEAT payload and a separate control flow for 
  OpenStack + HEAT 
- Wrote a complete template for MultiVDU OS + HEAT 
- Ironed out issues with jinja2 template and backend changes and tested end-to-end blue print generation flow 
#To Do
- Work on specifying cloud_init script input for Openstack Heat
- Test deployment with blueprint generated from VNF Onboarding

ETA 07/18 
#Note: Above ETA is based on the requirements identified so far. If some additional changes other than identified requirements are needed then , this ETA will need to be revised.

**Comment by nandkumarj** [comment]
Above checkin addresses MultiVDU for OS + HEAT. Closing the issue.
