### ISSUE TITLE
Analyze vCD + OVF specifications to futher incorporate additional parameters 

### ISSUE THREAD

**Issue by amolbjadhav** [vmware/bellhop#47]
we have created the list of ovf features and shared with Pankaj to discuss it further

**Comment by amolbjadhav** [comment]
The updated code for VCD +OVF is checked in.

**Comment by amolbjadhav** [comment]
We have received inputs from vmware team to add ovf extra config available for vCD. “Huge Pages” on 8/30.
We would modify the GUI, backend and Ovf template to support this extra config parameter.

**Comment by amolbjadhav** [comment]
In technical call on 8/31/2018 we come up with some additional features / suggestions as mentioned below:
1. Each VM should support multiple disk. 
The present VNF Onboarding tool support 1 disk per VM. In VCD + OVF combination, we need to support multiple disks per VM.
It needs GUI, backend and template modification.

2. The Network type in network configuration page should be "Isolated" "Direct" and "Routed" instead of "isolated", "bridged' and "natRouted"
It needs GUI, backend and template changes.

3. Currently we are supporting 16 CPUs per VM. We need to investigate and modify the Number of CPUs to its maximum limit per VM
It needs GUI, template change

4. Deploy and test the Direct network without adding its configuration in OVF file.

**Comment by amolbjadhav** [comment]
The following issues are fixed:
1. SR-IOV configuration is tested and bugs are fixed observed during testing.
2. Git upload support for HEAT and Ovf are added
3. Support for 128 CPUs per VM are added.

**Comment by ljilluzzi** [comment]
ETA on completion, including testing, is 09/14

**Comment by amolbjadhav** [comment]
The code is checked in for following features:
1. Support to multiple disks in Ovf package.
2. Support to Disk parameters like Bus Controller Type, Bus Number and Unit Number.

**Comment by varadep** [comment]
Provide support to select Guest operating system type

**Comment by amolbjadhav** [comment]
The code is tested and checked in.
