### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#5]
_From @nandkumarj on June 18, 2018 8:36_

This issue is for tracking task of code cleanup. Code  may require consistency in indentation , more comments for the sake of maintainability, documentation where required and possible,could be made more readable in some cases (Need to be identified)

_Copied from original issue: vanlittle/VNF-Onboarding#84_

**Comment by amolbjadhav** [comment]
Started the code clean up activity.
Removing the commented and unwanted code from the code base.

**Comment by ljilluzzi** [comment]
On track for 11/30 completion

**Comment by amolbjadhav** [comment]
The code has been clean cleaned. 
All stalled and unwanted changes are removed from repository
