### ISSUE TITLE
OSM R4 Support

### ISSUE THREAD

**Issue by varadep** [vmware/bellhop#52]
Add support for OSM R4 for VCD + VIO blueprints.

**Comment by amolbjadhav** [comment]
The workflow is added to support OSM R4 and the code is checked in

**Comment by amolbjadhav** [comment]
nNIC types are updated for OSM + VCD. Code is checked in.

**Comment by ljilluzzi** [comment]
OSM R4 install needs to be completed. ETA on completion is 10/09
Issue: need 40GB disk on VM

**Comment by amolbjadhav** [comment]
vNIC types for OSM Orchestrator are updated. The code is tested and checked in

**Comment by amolbjadhav** [comment]
Different blueprints are tested on OSM R4 and VIO 5.0 in dev lab

**Comment by ljilluzzi** [comment]
This can be closed

**Comment by amolbjadhav** [comment]
Waiting for OSM R4 Lab set up in Lab to test the OSM R4 with VCD 8.2 and VIO 4.0

**Comment by amolbjadhav** [comment]
The testing is completed. Hence closing the issue.
