### ISSUE TITLE
Creating new network with cloudify + Openstack

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#6]
_From @nandkumarj on June 18, 2018 8:23_

For Cloudify , network names that are captured  need to exist in VIM.  With this enhancement, this restriction won't be there and  it would be possible to create a new network using cloudify.

_Copied from original issue: vanlittle/VNF-Onboarding#83_

**Comment by ljilluzzi** [comment]
Validate that the last commit submitted is actually in the code base

**Comment by amolbjadhav** [comment]
Added the changes from code base and validated it.

**Comment by amolbjadhav** [comment]
We would update the license of all the files through different issue.
