### ISSUE TITLE
MultiVdu Support for TOSCA

### ISSUE THREAD

**Issue by vanlittle** [vmware/bellhop#7]
_From @amolbjadhav on June 14, 2018 12:56_

Add MultiVdu support to TOSCA
Change in backend and GUI to support MultiVdu TOSCA blueprint.

_Copied from original issue: vanlittle/VNF-Onboarding#82_

**Comment by ljilluzzi** [comment]
OK to close per #82?

**Comment by vanlittle** [comment]
82?

**Comment by vanlittle** [comment]
No, all of the old issues in the VNF-Onboarding project were auto closed when they were migrated to this repo.  

the issue is closed once the dev team has validated that it works, and the code is checked in and merged.

**Comment by ljilluzzi** [comment]
Code was checked in under old github issue #82.

**Comment by ljilluzzi** [comment]
To do: validate that the last commit that was submitted is actually in the code base

**Comment by amolbjadhav** [comment]
Validated the last commit that was submitted is actually in the code base  Would update all the files for license in separate issue.
